-- Migration para añadir la tabla de presentaciones de producto
CREATE TABLE IF NOT EXISTS public.product_presentation (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_tmpl_id BIGINT REFERENCES public.product_template(id) ON DELETE CASCADE,
    name VARCHAR(255) NOT NULL, -- ej. "UNIDAD"
    barcode VARCHAR(100),
    gross_weight NUMERIC(10,2) DEFAULT 0,
    weight_unit VARCHAR(50), -- ej. "kg", "lb"
    price_1 NUMERIC(15,2) DEFAULT 0,
    price_2 NUMERIC(15,2) DEFAULT 0,
    price_3 NUMERIC(15,2) DEFAULT 0,
    price_4 NUMERIC(15,2) DEFAULT 0,
    price_5 NUMERIC(15,2) DEFAULT 0,
    price_6 NUMERIC(15,2) DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Índices
CREATE INDEX IF NOT EXISTS idx_product_presentation_tmpl_id ON public.product_presentation(product_tmpl_id);

-- RLS
ALTER TABLE public.product_presentation ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Enable read access for all users" ON public.product_presentation FOR SELECT USING (true);
CREATE POLICY "Enable insert for authenticated users only" ON public.product_presentation FOR INSERT WITH CHECK (true);
CREATE POLICY "Enable update for users based on email" ON public.product_presentation FOR UPDATE USING (true);
CREATE POLICY "Enable delete for users based on email" ON public.product_presentation FOR DELETE USING (true);
